### ISSUE TITLE
Errors running gdsctools-0.16.4 standalone

### ISSUE THREAD

**Issue by cy-bao** [CancerRxGene/gdsctools#159]
[cbao@6c40 Projects]$gdsctools_anova --help
Traceback (most recent call last):
  File "/usr/local/bin/gdsctools_anova", line 9, in <module>
    load_entry_point('gdsctools==0.16.4', 'console_scripts', 'gdsctools_anova')()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 343, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2307, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.34-py2.7.egg/pkg_resources.py", line 2018, in load
    raise ImportError("%r has no %r attribute" % (entry,attr))
ImportError: <module 'gdsctools.pipelines' from '/usr/local/lib/python2.7/site-packages/gdsctools/pipelines/__init__.pyc'> has no 'anova_pipeline' attribute

**Comment by cokelaer** [comment]
Are you using the source code or pip ?

**Comment by cy-bao** [comment]
pip install gdsctools # 0.16

Then, I instsalled gdsctools-0.13.1. It worked for me. Thanks!

**Comment by cokelaer** [comment]
okay but so version 0.16.4 is failing then ? I have changed a piece of code related to the error you saw. There will be an updated version by tomorrow (0.17) in any case.
