### ISSUE TITLE
gdsc tool error

### ISSUE THREAD

**Issue by rajitnair** [CancerRxGene/gdsctools#173]
Whenever I am trying to install gdsctools using PIP command in Anaconda it always gives error like this in windows operating system
(C:\Users\Shadma Shareef\Anaconda2) C:\Users\Shadma Shareef>pip install gdsctools
Collecting gdsctools
  Using cached gdsctools-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\shadma~1\appdata\local\temp\pip-build-vjklop\gdsctools\setup.py", line 59, in <module>
        install_requires = open("requirements.txt").read()
    IOError: [Errno 2] No such file or directory: 'requirements.txt'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\shadma~1\appdata\local\temp\pip-build-vjklop\gdsctools\

**Comment by cokelaer** [comment]
hum, you are right. The requirements is missing. I will update the version to 1.0.1 
Meanwhile, you may use the release 1.0.0 here that contains all the files : https://github.com/CancerRxGene/gdsctools/releases  

```
pip install https://github.com/CancerRxGene/gdsctools/archive/1.0.0.tar.gz
```

**Comment by cokelaer** [comment]
I have now uploaded the version 1.0.1 tested locally. It should work.
