### ISSUE TITLE
Tissue filtered IC50 matrix may have columns with all NA results

### ISSUE THREAD

**Issue by howard-lightfoot** [CancerRxGene/gdsctools#185]
Error when running GDSC(ic50_file, drug_decode_file, genomic_feature_pattern='GF*csv'):

"
======================== Analysing BLCA data
...
  File ".../GDSCtools/env/lib/python3.9/site-packages/gdsctools-1.1.0-py3.9.egg/gdsctools/models.py", line 232, in <listcomp>
    (d, {"indices": ic50_parse.loc[d].index, "Y": ic50_parse.loc[d].values})
...
  File ".../GDSCtools/env/lib/python3.9/site-packages/pandas-1.3.5-py3.9-macosx-10.15-x86_64.egg/pandas/core/indexes/multi.py", line 3223, in _get_level_indexer
    raise KeyError(key)
KeyError: 1240
"
The key error relates to a drug with no results (all NA) once the IC50 object has been filtered for BLCA cell lines only. This reoccurs across tissue types. 

Solution: filter columns in IC50 using exisiting drop_drugs() method.

**Comment by howard-lightfoot** [comment]
Correction: error occurs when running ANOVA(ic50_file, gf_file)

**Comment by howard-lightfoot** [comment]
Similar error when running GDSC.create_data_packages_for_companies():

"
=========== Analysing company 1 out of 35 (AZ)
  ------- building TCGA BLCA sub directory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../GDSCtools/env/lib/python3.9/site-packages/gdsctools-1.1.0-py3.9.egg/gdsctools/gdsc.py", line 467, in create_data_packages_for_companies
    an.ic50.df = an.ic50.df[drug_decode_company.df.index]
  ...
  File ".../GDSCtools/env/lib/python3.9/site-packages/pandas-1.3.5-py3.9-macosx-10.15-x86_64.egg/pandas/core/indexing.py", line 1377, in _validate_read_indexer
    raise KeyError(f"{not_found} not in index")
KeyError: '[2559, 2611, 2612, 2613, 2614, 2615, 2616, 2617, 2618, 2619, 2620, 2621, 2622, 2623, 2624, 2625, 2626, 2627, 2628, 2629, 2630, 2631, 2632, 2633, 2634, 2635, 2636, 2637] not in index'
"
