### ISSUE TITLE
python 2.6 compat

### ISSUE THREAD

**Issue by cokelaer** [CancerRxGene/gdsctools#8]
```
ERROR: test.gdsctools.test_anova.test_anova_one_drug

Traceback (most recent call last):
File "/home/travis/miniconda/lib/python3.3/site-packages/nose/case.py", line 198, in runTest
self.test(*self.arg)
File "/home/travis/build/CancerRxGene/gdsctools/test/gdsctools/test_anova.py", line 57, in test_anova_one_drug
df = an.anova_one_drug('Drug_999_IC50')
File "/home/travis/build/CancerRxGene/gdsctools/gdsctools/anova.py", line 424, in anova_one_drug
mask = self.features.sum(axis=0) >= 3
File "/home/travis/miniconda/lib/python3.3/site-packages/pandas/core/ops.py", line 614, in wrapper
res = na_op(values, other)
File "/home/travis/miniconda/lib/python3.3/site-packages/pandas/core/ops.py", line 562, in na_op
result = lib.scalar_compare(x, y, op)
File "pandas/lib.pyx", line 706, in pandas.lib.scalar_compare (pandas/lib.c:12553)
TypeError: unorderable types: str() >= int()```

**Comment by cokelaer** [comment]
this was for python 3.4 and 3.3 
Python 2.6 will not be maintained.
